In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv("letter-recognition.data")
df

       T  2   8  3  5  1  8.1  13  0  6  6.1  10  8.2  0.1  8.3  0.2  8.4
0      I  5  12  3  7  2   10   5  5  4   13   3    9    2    8    4   10
1      D  4  11  6  8  6   10   6  2  6   10   3    7    3    7    3    9
2      N  7  11  6  6  3    5   9  4  6    4   4   10    6   10    2    8
3      G  2   1  3  1  1    8   6  6  6    6   5    9    1    7    5   10
4      S  4  11  5  8  3    8   8  6  9    5   6    6    0    8    9    7
...   .. ..  .. .. .. ..  ...  .. .. ..  ...  ..  ...  ...  ...  ...  ...
19994  D  2   2  3  3  2    7   7  7  6    6   6    4    2    8    3    7
19995  C  7  10  8  8  4    4   8  6  9   12   9   13    2    9    3    7
19996  T  6   9  6  7  5    6  11  3  7   11   9    5    2   12    2    4
19997  S  2   3  4  2  1    8   7  2  6   10   6    8    1    9    5    8
19998  A  4   9  6  6  2    9   5  3  1    8   1    8    2    7    2    8

[19999 rows x 17 columns]

In [3]:
display(df.shape)
df.dropna()
display(df.shape)

(19999, 17)

(19999, 17)

In [4]:
X = df.drop(columns = ["T"])
display(X)

y = df['T']
display(y)

       2   8  3  5  1  8.1  13  0  6  6.1  10  8.2  0.1  8.3  0.2  8.4
0      5  12  3  7  2   10   5  5  4   13   3    9    2    8    4   10
1      4  11  6  8  6   10   6  2  6   10   3    7    3    7    3    9
2      7  11  6  6  3    5   9  4  6    4   4   10    6   10    2    8
3      2   1  3  1  1    8   6  6  6    6   5    9    1    7    5   10
4      4  11  5  8  3    8   8  6  9    5   6    6    0    8    9    7
...   ..  .. .. .. ..  ...  .. .. ..  ...  ..  ...  ...  ...  ...  ...
19994  2   2  3  3  2    7   7  7  6    6   6    4    2    8    3    7
19995  7  10  8  8  4    4   8  6  9   12   9   13    2    9    3    7
19996  6   9  6  7  5    6  11  3  7   11   9    5    2   12    2    4
19997  2   3  4  2  1    8   7  2  6   10   6    8    1    9    5    8
19998  4   9  6  6  2    9   5  3  1    8   1    8    2    7    2    8

[19999 rows x 16 columns]

0        I
1        D
2        N
3        G
4        S
        ..
19994    D
19995    C
19996    T
19997    S
19998    A
Name: T, Length: 19999, dtype: object

In [5]:
encoder = LabelEncoder()
y = encoder.fit_transform(y)

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
display(X_train)

       2   8   3  5  1  8.1  13   0  6  6.1  10  8.2  0.1  8.3  0.2  8.4
5894   4  12   4  8  3    4  11  10  3    9   6    4    2   10    4    8
3728   1   1   2  1  0    8   9   2  2    7  12    8    1   10    0    8
8958   7  11  10  8  6    8   7   2  9   11   6    9    5    7    6    8
7671   2   3   3  2  2    6   7   5  5    9   7   10    2    9    4    9
5999   3   4   4  3  2    5   8   5  7    9   8    9    3   10    2    5
...   ..  ..  .. .. ..  ...  ..  .. ..  ...  ..  ...  ...  ...  ...  ...
11284  3   2   3  4  1    3   7   7  2    7   7   11    3    8    3   10
11964  2   4   4  3  3    8   7   3  5   10   6    7    2    8    4    9
5390   3   3   3  5  1    0   1   6  6    0   1    5    0    8    0    8
860    8  11   8  8  4    2  11   3  6   12  12    7    1   11    2    5
15795  2   6   3  4  2    1  10   3  5   11  11    9    0    8    2    7

[15999 rows x 16 columns]

In [7]:
scalar = StandardScaler()

X_train = scalar.fit_transform(X_train)
X_test = scalar.transform(X_test)

In [8]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()
model.add(Dense(128, activation='relu', input_shape=(16,)))
model.add(Dense(64, activation='relu'))
model.add(Dense(26, activation='softmax'))

E:\Avdhoot\GitHub\AG1713\Practicals\LP3\ML\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [9]:
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [10]:
model.fit(
    X_train,
    y_train,
    epochs=20,
    batch_size=32,
    validation_split=0.1
)

Epoch 1/20
450/450 ━━━━━━━━━━━━━━━━━━━━ 11s 10ms/step - accuracy: 0.6137 - loss: 1.4422 - val_accuracy: 0.7506 - val_loss: 0.8369
Epoch 2/20
450/450 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - accuracy: 0.7975 - loss: 0.6866 - val_accuracy: 0.8156 - val_loss: 0.6189
Epoch 3/20
450/450 ━━━━━━━━━━━━━━━━━━━━ 5s 8ms/step - accuracy: 0.8445 - loss: 0.5202 - val_accuracy: 0.8444 - val_loss: 0.4987
Epoch 4/20
450/450 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.8759 - loss: 0.4217 - val_accuracy: 0.8687 - val_loss: 0.4197
Epoch 5/20
450/450 ━━━━━━━━━━━━━━━━━━━━ 4s 4ms/step - accuracy: 0.8967 - loss: 0.3522 - val_accuracy: 0.8894 - val_loss: 0.3570
Epoch 6/20
450/450 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.9096 - loss: 0.3026 - val_accuracy: 0.9081 - val_loss: 0.3163
Epoch 7/20
450/450 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9226 - loss: 0.2643 - val_accuracy: 0.9075 - val_loss: 0.2947
Epoch 8/20
450/450 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9308 - loss: 0.2348 - val_accuracy: 0.9225 - val_loss: 0.2599
Epoch 9/20
450/450 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - accuracy: 0.9369 - loss: 0.2130 - val_accuracy: 0.9237 - val_loss: 0.2567
Epoch 10/20
450/450 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.9432 - loss: 0.1886 - val_accuracy: 0.9362 - val_loss: 0.2213
Epoch 11/20
450/450 ━━━━━━━━━━━━━━━━━━━━ 6s 11ms/step - accuracy: 0.9476 - loss: 0.1734 - val_accuracy: 0.9369 - val_loss: 0.2075
Epoch 12/20
450/450 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - accuracy: 0.9524 - loss: 0.1572 - val_accuracy: 0.9369 - val_loss: 0.2096
Epoch 13/20
450/450 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - accuracy: 0.9549 - loss: 0.1465 - val_accuracy: 0.9362 - val_loss: 0.1989
Epoch 14/20
450/450 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.9600 - loss: 0.1348 - val_accuracy: 0.9375 - val_loss: 0.1956
Epoch 15/20
450/450 ━━━━━━━━━━━━━━━━━━━━ 6s 10ms/step - accuracy: 0.9633 - loss: 0.1229 - val_accuracy: 0.9388 - val_loss: 0.1894
Epoch 16/20
450/450 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - accuracy: 0.9642 - loss: 0.1133 - val_accuracy: 0.9438 - val_loss: 0.1760
Epoch 17/20
450/450 ━━━━━━━━━━━━━━━━━━━━ 6s 11ms/step - accuracy: 0.9675 - loss: 0.1084 - val_accuracy: 0.9500 - val_loss: 0.1673
Epoch 18/20
450/450 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - accuracy: 0.9697 - loss: 0.0980 - val_accuracy: 0.9388 - val_loss: 0.1767
Epoch 19/20
450/450 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - accuracy: 0.9715 - loss: 0.0940 - val_accuracy: 0.9475 - val_loss: 0.1705
Epoch 20/20
450/450 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - accuracy: 0.9749 - loss: 0.0873 - val_accuracy: 0.9419 - val_loss: 0.1685

In [11]:
y_pred = model.predict(X_test)

125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step

In [12]:
loss,accuracy = model.evaluate(X_test, y_test)

print("Accuracy: ",accuracy)

125/125 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - accuracy: 0.9417 - loss: 0.1673
Accuracy:  0.9417499899864197

In [13]:
predicted_class = np.argmax(y_pred[0])

print(predicted_class)

23

In [14]:
letter = encoder.inverse_transform([predicted_class])

print(letter)

['X']